### ISSUE TITLE
Int32 casting does not work

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cq-gen#113]
### Describe the bug

```
Error testing aws_lightsail_load_balancers: error/s occurred during test, resource: . summary: failed bulk insert on table "aws_lightsail_load_balancers": table aws_lightsail_load_balancers insert failed column public_ports expected TypeIntArray got []int32, details , resource: . summary: table aws_lightsail_load_balancers insert failed column public_ports expected TypeIntArray got []int32, details
```

### Expected Behavior

it should cast int32 to int automatically without any manual resolvers

### Steps to Reproduce

try to test aws_lightsail_load_balancers without generated resolver for `public_ports` column

### Provider and CloudQuery version

-

**Comment by hermanschaaf** [comment]
This was fixed in https://github.com/cloudquery/cq-provider-sdk/pull/433
