### ISSUE TITLE
Define replace patterns for documentation

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cq-gen#75]
Add ability to set replace patterns for documentation
```
documentation_replace_patterns = [ 
  {
    find = " this member is required."
    replace_with = ""
  }
]

**Comment by hermanschaaf** [comment]
Yes! Some feature for this will be very useful. Maybe we can support replacement regex(es)? Currently I'm trying to deal with descriptions of the form `Kind: The kind of resource, in this case "Service".` where I'd like to get rid of the `Kind: ` prefix.
