### ISSUE TITLE
`package cannot be nil` if description of resource is set 

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cq-gen#76]
### Describe the bug

generate fails with `package cannot be nil` with next config
```
resource "azure" "sql" "servers" {
  description = "Azure sql server"
  path        = "github.com/Azure/azure-sdk-for-go/services/sql/mgmt/2014-04-01/sql.Server"
}
```

### Expected Behavior

it should not fail

### Steps to Reproduce

add description field and try to generate a resource

### Provider and CloudQuery version

-

**Comment by hermanschaaf** [comment]
I think this must have been fixed a while back, I cannot reproduce it anymore.
