### ISSUE TITLE
Ensure `cq-gen` generates code that conforms to our linting rules

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cq-gen#99]
Extracted from https://github.com/cloudquery/cq-provider-digitalocean/pull/96#pullrequestreview-978112825

**Comment by amanenk** [comment]
It looks like a duplicate of #70

**Comment by erezrokah** [comment]
Yes! Thanks for the tip. Closing in favor of https://github.com/cloudquery/cq-gen/issues/70
